### ISSUE TITLE
How to write the demonstrations ?

### ISSUE THREAD

**Issue by yyq** [MohammadrezaPourreza/Few-shot-NL2SQL-with-prompting#16]
Thank you for the research and the code. 
I'm trying this method on another dataset, I want to write some similar demonstrations for all the prompts.
I want to konw, when you write the demonstrations, did you pick example from the dataset randomly ? or with some strategy ?

**Comment by MohammadrezaPourreza** [comment]
Thank you so much for your interest in this work, based on recent papers on prompting it is suggested to always choose the most complex examples.

**Comment by yyq** [comment]
Thanks.
