### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tapdiego-amzn** [MohammadrezaPourreza/Few-shot-NL2SQL-with-prompting#17]
Thank you for your project. However, I'm unable to find its license — would it be possible for you to add one so the terms of use are clear? https://choosealicense.com/ might be a good way for you to find a license that works for your project. Thanks in advance.

**Comment by MohammadrezaPourreza** [comment]
I've added the license thanks

**Comment by tapdiego-amzn** [comment]
Thank you!
