### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by huimoran** [MohammadrezaPourreza/Few-shot-NL2SQL-with-prompting#20]
Hello, I would like to ask, in the text2sql experiment, 
is your database schema bound with natural language (referring to the question based on the database schema),
 or is the natural language question independent of the database schema (according to the natural language question to find the matching database schema into the corresponding prompt)?

**Comment by MohammadrezaPourreza** [comment]
@huimoran Hello, thank you for your interest in our work. Natural language questions are bounded with database schema.

**Comment by huimoran** [comment]
Ok, I see. Thank you for your answer.
