### ISSUE TITLE
How long is your your predict script's runtime? 

### ISSUE THREAD

**Issue by bigbigwatermalon** [MohammadrezaPourreza/Few-shot-NL2SQL-with-prompting#3]
The Spider Submission Guideline says "Please restrict your predict script's runtime to under two hours and up to two models per submission." 
I have tried your codes, and it takes about 1 hour to predict 100+ sqls. So it will take more than 2 hours to predict the whole dev dataset with your codes. 
I wonder how you manage this problem, or whether the 2 hours restriction of spider matters. 
Thanks a lot!

**Comment by MohammadrezaPourreza** [comment]
Hey,
Yes we had the same problem, so we sent our submission to Tao and they waived the 2 hour restriction. Thanks to them.
